analyzer:
  include: package:lints/recommended.yaml

  exclude:
    - build/**
    - dead_code/**

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    close_sinks: ignore
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error

  linter:
    rules:
      - always_declare_return_types
      - always_put_required_named_parameters_first
      - cancel_subscriptions
      - close_sinks
      - combinators_ordering
      - comment_references
      - invalid_case_patterns
      - library_annotations
      - one_member_abstracts
      - only_throw_errors