name: keo_flutter
description: Keo Flutter project.
version: 1.0.0+32
environment:
  sdk: ">=2.42.0 <= 3.2.6"
dependencies:
  autocomplete_textfield: ^2.0.1
  material_dialogs: ^1.1.4
  badges: ^3.1.2
  basic_utils: ^5.7.0
  carousel_slider: ^4.0.0
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.0
  cached: 1.6.4
  cached_annotation: ^1.6.0
  csc_picker: ^0.2.7
  device_info_plus: ^9.1.0
  dio: ^5.0.3
  dropdown_search: ^5.0.6
  multi_dropdown: ^2.1.0
  dropdown_button2: ^2.3.9
  dotted_border: 2.1.0
  equatable: ^2.0.0
  easy_scroll_animation: ^1.0.2
  exif: ^3.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_i18n: ^0.35.0
  flutter_autocomplete_label: ^1.0.0
  flutter_bloc: ^8.0.0
  flutter_chip_tags: ^2.0.2
  flutter_exif_rotation: ^0.5.1
  flutter_fast_forms: ^15.0.0
  flutter_pin_code_fields: ^2.2.0
  flutter_redux: ^0.10.0
  flutter_svg: ^2.0.8
  flutter_svg_provider: ^1.0.6
  flutter_switch: ^0.3.2
  flutter_native_image: ^0.0.6+1
  flutter_profile_picture: ^2.0.0
  fluro: ^2.0.0
  formz: ^0.6.0
  font_awesome_flutter: ^10.7.0
  geocode: ^1.0.3
  geolocator: ^11.0.0
  google_sign_in: ^6.1.6
  google_maps_flutter: ^2.5.3
  intl: ^0.19.0
  image: ^4.1.4
  image_picker: ^1.0.7
  lite_rolling_switch: ^1.0.1
  logging: any
  logging_to_logcat: ^1.0.0
  money2: ^4.0.0
  openapi_generator: 4.13.1
  openapi_generator_annotations: 4.13.1
  observable_ish: ^4.0.8
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  pointycastle: ^3.7.4
  provider: ^6.0.5
  quantity_input: ^1.0.2
  re_reselect: ^1.0.0
  rsa_encrypt: ^2.0.0
  rxdart: ^0.27.0
  sqflite: ^2.2.8+4
  sqflite_common: ^2.4.5+1
  shared_preferences: ^2.0.15
  scrollable_list_tab_scroller: ^1.1.2
  smooth_page_indicator: ^1.1.0
  stomp_dart_client: ^1.0.2
  switcher: ^1.0.0
  toast: ^0.3.0
  timelines: ^0.1.0
  toggle_switch: ^2.1.0
  uuid: ^4.3.3
  video_player: ^2.8.1
  sealapi:
    path: lib/openapi/sealapi
  sealuser:
    path: lib/openapi/sealuser
  flutter_layout_grid: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.2.4

dev_dependencies:
  build_runner: 2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.2
  faker: ^2.1.0
  analyzer: ^6.4.0
  lints: ^3.0.0
  test: ^1.24.9

dependency_overrides:
  http: ^1.0.0
  meta: ^1.11.0
  analyzer: ^6.4.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/process_timeline/
    - assets/images/new_ui/
    - assets/images/new_ui/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
